name: For the rearc quest deployment, perform both the build and deployment activities together within the same chained jobs.
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: false
        default: 'debug' 
        type: choice
        options:
        - info
        - warning
        - debug 
      
jobs:
  call-docker-image-build-workflow:
    uses: ./.github/workflows/docker-image-build.yml
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  call-infra-deploy-workflow:
    needs: call-docker-image-build-workflow
    uses: ./.github/workflows/infra-deploy.yml