name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      AWS_REGION: us-east-1
    outputs:
      image_tag: ${{ steps.docker.outputs.image_tag }}      
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
        
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1    

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      
      - name: Build App
        run: npm install

      - name: Build, tag, and push image to Amazon ECR
        id: docker
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: binu-rearc-quest
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          echo "::set-output name=image_tag::$IMAGE_TAG"

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
    outputs:
      url: ${{ steps.terraform.outputs.url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2      
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.4

      - name: Terraform Deploy
        id: terraform
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: binu-rearc-quest
          IMAGE_TAG: ${{ needs.build.outputs.image_tag }}
        run: |
          cd terraform
          terraform init -backend-config="bucket=binu-rearc-quest-terraform-01" -backend-config="key=binu-rearc-quest/${{ env.ENV_NAME }}.tfstate" -backend-config="region=us-east-1"
          terraform apply -auto-approve

      - run: echo ${{ steps.terraform.outputs.rearc_quest_box_ip }}
      
      - run: echo ${{ steps.terraform.outputs.exitcode }}
          
      - name: executing remote ssh commands using ssh key
        id: remote-ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ steps.terraform.outputs.rearc_quest_box_ip }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY_PEM }}
          port: 22
          script: whoami
          
